name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  checkbuilder:
    runs-on: ubuntu-latest
    outputs:
      builderupdated: ${{ steps.check.outputs.updated }}
      builderref: ${{ steps.check.outputs.curref }}
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - id: check
      run: |
        lastref=`cat .github/utils/last_build_ref | tr -d '[:space:]'`
        curref=`git ls-remote https://github.com/jayanthkoushik/build-webpage HEAD | cut -f1 | cut -c-6`
        if [ "$lastref" = "$curref" ]; then
          updated=0
        else
          updated=1
        fi
        echo "::set-output name=updated::${updated}"
        echo "::set-output name=curref::${curref}"

  build:
    needs: checkbuilder
    # if: ${{ needs.checkbuilder.outputs.builderupdated == 1 }}
    if: ${{ 0 == 1 }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/setup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tagbuild:
    needs: checkbuilder
    if: ${{ needs.checkbuilder.outputs.builderupdated == 1 }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        ref: gh-pages
    - run: |
        git tag "builder-${{ needs.checkbuilder.outputs.builderref }}"
        git push --tags
