name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    needs: checkbuilder
    if: ${{ needs.checkbuilder.outputs.builderupdated == 1 || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/setup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
