name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - id: getlastver
      uses: juliangruber/read-file-action@master
      with:
        path: ./.github/utils/last_build_version
    - id: getcurver
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: jayanthkoushik
        repo: build-webpage
    - run: test ${{steps.getlastver.outputs.content}} != ${{steps.getcurver.outputs.release}}
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/setup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
