name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      builderupdated: ${{ steps.checkup.outputs.updated }}
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - id: checkup
      run: |
        lastref=`cat .github/utils/last_build_ref | tr -d '[:space:]'`
        curref=`git ls-remote https://github.com/jayanthkoushik/build-webpage HEAD | cut -f1`
        if [ "$lastref" = "$curref" ]; then
          updated=0
        else
          updated=1
        fi
        echo "::set-output name=updated::${updated}"
    - run: echo ${{ steps.checkup.outputs.updated }}
  build:
    needs: check
    if: ${{ needs.check.outputs.builderupdated == 1 }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/setup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
