name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - id: checkup
      run: sh .github/utils/check_builder_updated.sh
    outputs:
      builderupdated: ${{ steps.checkup.outputs.updated }}
  build:
    needs: check
    if: needs.check.outputs.builderupdated
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/setup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
