name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jayanthkoushik/paje@master
      with:
        setupscript: |
          cp index.md /www/
          cp _includes/* /www/_includes/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
