name: Build project website and deploy to gh-pages

on:
  push:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - run: sh .github/utils/check_builder_updated.sh
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/setup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
